#!/bin/bash --verbose
echo "start bootstrap test"
make clean>/dev/null
cp ./bin/spitbol  tbol
make BASEBOL=./tbol
mv s.lex tbol.lex.0
mv s.s tbol.s.0
cp spitbol tbol
make BASEBOL=./tbol
mv s.lex tbol.lex.1
mv s.s tbol.s.1
cp spitbol tbol
make 
make tcc-makefile BASEBOL=./tbol
mv s.lex tbol.lex.2
mv s.s tbol.s.2
echo "comparing generated .s files"
diff tbol.s.1 tbol.s.2
echo "end bootstrap test"
